pipeline {
    agent any
    stages {
        stage('S2I → Buildah (smoke)') {
  agent {
    kubernetes {
      // ⚠️ Sửa đúng tên Cloud bạn cấu hình trong Manage Jenkins → Clouds
      cloud 'Kubernetes'                 // ví dụ: 'kubernetes', 'okd-prod', 'okd'
      inheritFrom 's2i-nodejs-fe'        // ⚠️ phải trùng NAME Pod Template trong UI    
      showRawYaml true                   // in manifest ra console để debug
    }
  }
  options { timeout(time: 10, unit: 'MINUTES') }
  steps {
    container('s2i') {
      sh 'bash -lc "echo Hello from bash"'
    }
    container('buildah') {
      sh 'echo Buildah container OK'
    }
  }
}

    }
}